version : "3"

services:
  hms_adminpanel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - .:/hms_admin_panel
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    networks:
      - hms_network

networks:
    hms_network:
      external: true

